package com.teamone.hackathon.common.utils

import com.teamone.hackathon.main.domain.model.Logistic
import com.teamone.hackathon.main.domain.model.Logistics

fun mockData(): Logistics =
    Logistics(
        listOf(
            Logistic(
                "02/02/2023",
                6,
                "JARDINERA",
                1,
                0,
                1,
                205,
                0,
                205
            ),
            Logistic(
                "02/02/2023",
                7,
                "JARDINERA",
                1,
                3,
                1,
                240,
                80,
                320
            ),
            Logistic(
                "02/02/2023",
                2,
                "JARDINERA",
                0,
                1,
                1,
                100,
                0,
                100
            ),
            Logistic(
                "02/02/2023",
                6,
                "JARDINERA",
                1,
                0,
                1,
                205,
                0,
                205
            ),
            Logistic(
                "02/02/2023",
                6,
                "JARDINERA",
                1,
                0,
                1,
                205,
                0,
                205
            ),
            Logistic(
                "02/02/2023",
                6,
                "JARDINERA",
                1,
                0,
                1,
                205,
                0,
                205
            ),
            Logistic(
                "02/02/2023",
                6,
                "JARDINERA",
                1,
                0,
                1,
                205,
                0,
                205
            ),
            Logistic(
                "02/02/2023",
                6,
                "JARDINERA",
                1,
                0,
                1,
                205,
                0,
                205
            ),            Logistic(
                "02/02/2023",
                2,
                "JARDINERA",
                0,
                1,
                1,
                100,
                0,
                100
            )
        )
    )

